[tool.poetry]
name = "YetAnotherPicSearch4Telegram"
version = "1.0.0"
description = "Yet Another Picture Search bot for Telegram"
authors = ["NekoAria"]
license = "GPL-3.0-only"
readme = "README.md"
packages = [
    { include = "YetAnotherPicSearch4Telegram" },
]
homepage = "https://github.com/NekoAria/YetAnotherPicSearch4Telegram"
repository = "https://github.com/NekoAria/YetAnotherPicSearch4Telegram"
keywords = ["telegram", "bot", "saucenao", "pixiv", "danbooru", "doujin", "anime", "ascii2d", "iqdb", "exhentai"]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = {extras = ["speedups"], version = "^3.8.4"}
arrow = "^1.2.3"
cachetools = "^5.3.0"
loguru = "^0.6.0"
lxml = "^4.9.2"
PicImageSearch = "^3.9.0"
pydantic = {extras = ["dotenv"], version = "^1.10.7"}
pyquery = "^2.0.0"
Telethon = "^1.27.0"
tenacity = "^8.2.2"
yarl = "^1.8.2"

[tool.poetry.extras]
socks = ["aiohttp_socks"]

[tool.poetry.dev-dependencies]

[tool.mypy]
python_version = "3.8"
plugins = [
    "pydantic.mypy"
]
ignore_missing_imports = true
implicit_reexport = true
pretty = true
show_error_codes = true
strict = true

[tool.ruff]
select = ["F", "E", "W", "I"]
target-version = "py38"
line-length = 120

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
