[tool.poetry]
name = "YetAnotherPicSearch4Telegram"
version = "1.0.0"
description = "Yet Another Picture Search bot for Telegram"
authors = ["NekoAria"]
license = "GPL-3.0-only"
readme = "README.md"
packages = [
    { include = "YetAnotherPicSearch4Telegram" },
]
homepage = "https://github.com/NekoAria/YetAnotherPicSearch4Telegram"
repository = "https://github.com/NekoAria/YetAnotherPicSearch4Telegram"
keywords = ["telegram", "bot", "saucenao", "pixiv", "danbooru", "doujin", "anime", "ascii2d", "iqdb", "exhentai"]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = {extras = ["speedups"], version = "^3.8.3"}
arrow = "^1.2.3"
cachetools = "^5.3.0"
loguru = "^0.6.0"
PicImageSearch = "^3.7.8"
pydantic = {extras = ["dotenv"], version = "^1.10.4"}
pyquery = "^2.0.0"
Telethon = "^1.26.1"
tenacity = "^8.1.0"
yarl = "^1.8.2"

[tool.poetry.dev-dependencies]

[tool.mypy]
python_version = "3.8"
ignore_missing_imports = true
implicit_reexport = true
pretty = true
show_error_codes = true
strict = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
