[tool.poetry]
name = "YetAnotherPicSearch4Telegram"
version = "1.0.0"
description = "Yet Another Picture Search bot for Telegram"
authors = ["NekoAria"]
license = "GPL-3.0-only"
readme = "README.md"
packages = [
    { include = "YetAnotherPicSearch4Telegram" },
]
homepage = "https://github.com/NekoAria/YetAnotherPicSearch4Telegram"
repository = "https://github.com/NekoAria/YetAnotherPicSearch4Telegram"
keywords = ["telegram", "ascii2d", "baidu", "e-hentai", "google", "iqdb", "saucenao", "tracemoe", "yandex", "anime", "danbooru", "doujin", "pixiv"]

[tool.poetry.dependencies]
python = "^3.8"
arrow = "^1.2.3"
cachetools = "^5.3.1"
httpx = "^0.24.1"
loguru = "^0.7.0"
lxml = "^4.9.3"
PicImageSearch = "^3.9.5"
Pillow = "^10.0.0"
pydantic = {extras = ["dotenv"], version = "^2.2.1"}
pydantic-settings = "^2.0.3"
pyquery = "^2.0.0"
python-socks = {extras = ["asyncio"], version = "^2.3.0", optional = true}
socksio = { version = "^1.0.0", optional = true }
Telethon = "^1.29.3"
tenacity = "^8.2.3"

[tool.poetry.extras]
socks = ["python-socks", "socksio"]

[tool.poetry.dev-dependencies]

[tool.mypy]
python_version = "3.8"
plugins = [
    "pydantic.mypy"
]
ignore_missing_imports = true
implicit_reexport = true
pretty = true
show_error_codes = true
strict = true

[tool.ruff]
select = ["F", "E", "W", "I", "UP"]
target-version = "py38"
line-length = 120

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
